version: '3.9'

services:

  delivery-service:
    build: .
    container_name: delivery-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  postgres:
    image: postgres:15
    container_name: delivery-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: deliverydb
    ports:
      - "5432:5432"
    restart: always